name: Flutter CI (test_ci_cd)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # Clone repo test_ci_cd (otomatis sesuai repo ini)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"

      # Install dependencies
      - run: flutter pub get

      # Run tests
      - run: flutter test

      # Build APK
      - run: flutter build apk --release

      # Build AppBundle
      - run: flutter build appbundle --release

      # Upload artifact ke GitHub (opsional, biar bisa download dari tab Actions)
      - name: Upload APK to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload ke Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
