name: Flutter CI (test_ci_cd)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # Clone repo test_ci_cd (otomatis sesuai repo ini)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      # Install dependency
      - name: Install dependencies
        run: flutter pub get

      # Jalankan test
      - name: Run Flutter tests
        run: flutter test

      # Build APK
      - name: Build APK (Android)
        run: flutter build apk --release

      # Build AppBundle
      - name: Build AppBundle (Android)
        run: flutter build appbundle --release
